import React from 'react';
import { Database, FileCode, CheckCircle, Server, ArrowDown } from 'lucide-react';

export const Architecture: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto px-6 lg:px-8 py-16 space-y-20">
      
      <div className="text-center">
        <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl mb-4">
          Technical Architecture & Data Flow
        </h2>
        <p className="text-lg text-gray-400 max-w-3xl mx-auto">
          Merito leverages Midnight's Compact language to separate private identity verification from public state mutation.
        </p>
      </div>

      {/* Flow Steps */}
      <div className="relative">
        <div className="absolute left-1/2 transform -translate-x-1/2 h-full w-1 bg-indigo-900/30 hidden md:block"></div>
        
        <div className="space-y-12">
          {[
            {
              icon: <Database className="w-6 h-6 text-white" />,
              title: "1. Private Identity Linking",
              desc: "The user loads their Verifiable Credential (VC) (e.g., 'Senior Developer Certification') into their local wallet storage. This remains in the Midnight Private State, inaccessible to the public."
            },
            {
              icon: <Server className="w-6 h-6 text-white" />,
              title: "2. Local ZK Circuit Generation",
              desc: "The Merito TypeScript SDK runs locally on the client. It takes the VC and the user's vote as private inputs. It generates a Zero-Knowledge Proof (ZKP) asserting eligibility without leaking the VC data."
            },
            {
              icon: <CheckCircle className="w-6 h-6 text-white" />,
              title: "3. Compact Verification",
              desc: "The transaction containing the ZKP and the public Vote Hash is submitted to the Midnight Ledger. The `MeritoWeightingEngine.compact` contract verifies the proof against the circuit constraints."
            },
            {
              icon: <FileCode className="w-6 h-6 text-white" />,
              title: "4. State Mutation",
              desc: "Upon successful verification, the contract updates the public 'Vote Tally' state. The linkage between the specific VC and the vote remains mathematically severed."
            }
          ].map((step, idx) => (
            <div key={idx} className="relative flex flex-col md:flex-row items-center md:items-start gap-8">
              <div className="flex-shrink-0 z-10 bg-indigo-600 rounded-full p-4 border-4 border-midnight-950 shadow-xl shadow-indigo-900/20">
                {step.icon}
              </div>
              <div className="flex-1 bg-midnight-800 p-6 rounded-xl border border-white/5 w-full">
                <h3 className="text-xl font-bold text-white mb-2">{step.title}</h3>
                <p className="text-gray-400">{step.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Contract Deep Dive */}
      <div className="grid md:grid-cols-2 gap-8 mt-16">
        <div className="bg-midnight-950 border border-indigo-500/30 rounded-2xl p-8">
          <h3 className="text-2xl font-bold text-white mb-6">MeritoWeightingEngine.compact</h3>
          <p className="text-gray-400 mb-6">
            The core contract is designed to be minimal and stateless regarding user identity. It functions purely as a verifier.
          </p>
          <div className="bg-black/50 p-4 rounded-lg font-mono text-sm text-indigo-300">
            // Conceptual Verification Logic<br/>
            export circuit verifyVote(proof, publicInput) &#123;<br/>
            &nbsp;&nbsp;verify(proof); // ZK Check<br/>
            &nbsp;&nbsp;assert(proof.nullifier != exists); // Sybil Check<br/>
            &nbsp;&nbsp;return true;<br/>
            &#125;
          </div>
        </div>

        <div className="bg-midnight-950 border border-indigo-500/30 rounded-2xl p-8">
          <h3 className="text-2xl font-bold text-white mb-6">The ZK Proof Assertions</h3>
          <p className="text-gray-400 mb-4">
            The ZKP generated by our SDK simultaneously proves three non-negotiable assertions to the ledger:
          </p>
          <ul className="space-y-4">
            <li className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-1 flex-shrink-0" />
              <span className="text-gray-300"><strong>Proof of Identity Uniqueness:</strong> The user has not voted in this epoch (via Nullifier).</span>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-1 flex-shrink-0" />
              <span className="text-gray-300"><strong>Proof of Possession:</strong> The user holds a valid VC signed by a trusted issuer.</span>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-1 flex-shrink-0" />
              <span className="text-gray-300"><strong>Proof of Calculation:</strong> The Vote Weight was calculated correctly based on the VC metadata (e.g., years of experience).</span>
            </li>
          </ul>
        </div>
      </div>

    </div>
  );
};